apiVersion: v1
kind: Service
metadata:
  name: external-lb-prometheus-server
  namespace: default
  labels:
    app: prometheus-server
spec:
  type: LoadBalancer
  selector:
    app: prometheus-server
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP

