{
 "title": "Pulse",
 "description": "test",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "vertx_vertx_net_clients_connections_Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_vertx_net_clients_connections_Count"
    }
   ]
  },
  {
   "title": "kafka_producer_producer_metrics_requests_in_flight",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(kafka_producer_producer_metrics_requests_in_flight) by (k8s_pod_name), 0.001)"
    }
   ]
  },
  {
   "title": "kafka_producer_producer_metrics_request_rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_metrics_request_rate) by (k8s_pod_name)"
    }
   ]
  },
  {
   "title": "kafka_producer_producer_metrics_request_latency_avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_producer_producer_metrics_request_latency_avg) by (k8s_pod_name)"
    }
   ]
  },
  {
   "title": "kafka_producer_producer_metrics_outgoing_byte_rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_producer_producer_metrics_outgoing_byte_rate) by (k8s_pod_name)"
    }
   ]
  },
  {
   "title": "kafka_producer_producer_metrics_waiting_threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_metrics_waiting_threads) by (k8s_pod_name)"
    }
   ]
  },
  {
   "title": "kafka_producer_producer_metrics_network_io_rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_metrics_network_io_rate) by (k8s_pod_name)"
    }
   ]
  },
  {
   "title": "kafka_producer_producer_metrics_connection_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_metrics_connection_count) by (k8s_pod_name)"
    }
   ]
  },
  {
   "title": "kafka_producer_producer_metrics_record_error_rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_metrics_record_error_rate) by (k8s_pod_name)"
    }
   ]
  },
  {
   "title": "kafka_producer_producer_metrics_bufferpool_wait_time_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_producer_producer_metrics_bufferpool_wait_time_total) by (k8s_pod_name)"
    }
   ]
  },
  {
   "title": "kafka_producer_producer_metrics_batch_size_avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_producer_producer_metrics_batch_size_avg) by (k8s_pod_name)"
    }
   ]
  },
  {
   "title": "kafka_producer_producer_metrics_batch_size_avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_producer_producer_metrics_batch_size_avg) by (k8s_pod_name)"
    }
   ]
  },
  {
   "title": "kafka_producer_producer_metrics_io_ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_producer_producer_metrics_io_ratio) by (k8s_pod_name)"
    }
   ]
  }
 ]
}